// Enemy definitions are separated from index.html so they can be edited by hand.
// ET contains monster data. ENEMY_RANK contains rank multipliers and sync settings.
window.AMC_ENEMIES=(function(){
 function scale(lv){return Math.pow(Math.max(1,lv),1.55);}
 function mob(jp,lv,el,at,asset,opt){opt=opt||{};const hp=opt.hp||Math.round(42+scale(lv)*18),atk=opt.atk||Math.round(7+lv*1.65),def=opt.def||Math.round(4+lv*.55),spd=opt.spd==null?Math.max(.42,Math.min(1.12,.62+lv*.003)):opt.spd,r=opt.r||Math.max(11,Math.min(24,12+lv/12));const e={jp,asset:asset||jp,el,at,hp,def,atk,spd,r,col:opt.col||'#b8c8d8',exp:Math.round(hp*.5),windup:opt.windup||(at==='charge'?1.05:at==='ranged'?1.35:1.55),recover:opt.recover||1.2};if(at==='ranged'){e.range=opt.range||Math.round(280+lv*2.4);e.shotSpd=opt.shotSpd||Math.min(7.2,4.2+lv*.025);e.burst=opt.burst||1;}if(at==='charge')e.dash=opt.dash||Math.min(17,10+lv*.06);if(opt.mv)e.mv=opt.mv;return e;}
 const ET={
  slime:mob('マナスライム',1,'水','melee','マナスライム',{col:'#3aa0ff'}),hornRabbit:mob('ホーンラビット',2,'風','melee','ホーンラビット',{spd:1.05,col:'#d8e8b0'}),manaBunny:mob('マナうさぎ',3,'風','melee','ホーンラビット',{spd:1.08,col:'#dff7ff'}),manaWolf:mob('マナウルフ',6,'土','charge','マナウルフ',{col:'#b07a4a'}),manaHawk:mob('マナホーク',11,'風','ranged','マナホーク',{col:'#dfe8a0',burst:2}),manaBear:mob('マナベア',32,'土','melee','マナベア',{col:'#b89060',r:21}),
  goblin:mob('ゴブリン',5,'土','melee','ゴブリン',{col:'#7ab060'}),goblinArcher:mob('ゴブリンアーチャー',6,'風','ranged','ゴブリンアーチャー',{col:'#e6b531',burst:2}),goblinMage:mob('ゴブリンメイジ',8,'火','ranged','ゴブリンメイジ',{col:'#c070ff',burst:2}),hobgoblin:mob('ホブゴブリン',20,'土','melee','ホブゴブリン',{col:'#8a8f9a',r:20}),goblinRider:mob('ゴブリンライダー',19,'風','charge','ゴブリンライダー',{col:'#8fd070'}),
  mandrake:mob('マンドレイク',11,'土','ranged','マナディア',{col:'#a6d070'}),manaFlower:mob('マナフラワー',12,'水','ranged','シルフ',{col:'#ff9ed0'}),myconid:mob('マイコニド',13,'土','ranged','ノーム',{col:'#b89a70'}),scarab:mob('スカラベ',14,'土','charge','ロックスライム',{col:'#c8a060'}),pudding:mob('プリン',13,'水','melee','エリクサースライム',{col:'#d0c070'}),gnome:mob('ノーム',15,'土','ranged','ノーム',{col:'#d8b070',burst:2}),aquaJelly:mob('アクアジェリー',14,'水','melee','アクアスライム',{col:'#8fd8ff'}),manaFish:mob('マナフィッシュ',15,'水','charge','ケルピー',{col:'#7fd0e8'}),mudGolem:mob('マッドゴーレム',16,'土','melee','ロックスライム',{col:'#8a6f48',r:22}),
  killerBee:mob('キラービー',20,'風','charge','マナホーク',{col:'#ffe04a'}),sylph:mob('シルフ',20,'風','ranged','シルフ',{col:'#c0ffd0',burst:2,mv:'circle'}),prism:mob('プリズムバード',20,'水','ranged','プリズムバード',{col:'#dffaff',burst:4,mv:'circle'}),saberCat:mob('サーベルキャット',22,'風','charge','サーベルキャット',{col:'#d9c090'}),harpy:mob('ハーピー',23,'風','ranged','ハーピー',{col:'#d0d8ff',burst:2}),giantSpider:mob('ジャイアントスパイダー',23,'土','melee','コカトリス',{col:'#6f6080'}),merman:mob('マーマン',24,'水','melee','ケルピー',{col:'#6fc8e0'}),kelpie:mob('ケルピー',24,'水','charge','ケルピー',{col:'#7fe0ff'}),lizardman:mob('リザードマン',25,'水','melee','サラマンダー',{col:'#7cc080'}),wisplace:mob('ウィスプレイス',26,'無','ranged','ウィル・オ・ウィスプ',{col:'#b9a8ff',burst:3}),poltergeist:mob('ポルターガイスト',26,'無','ranged','スピリット',{col:'#a890d8',burst:3}),stoneGolem:mob('ストーンゴーレム',28,'土','melee','ロックスライム',{col:'#9a927f',r:23}),cockatrice:mob('コカトリス',28,'風','charge','コカトリス',{col:'#c8b070'}),tanuki:mob('化け狸',29,'無','ranged','ホーンラビット',{col:'#a87850',burst:2}),gemSlime:mob('ジェムスライム',24,'水','charge','ジェムスライム',{col:'#aef0ff'}),
  drake:mob('ドレイク',30,'火','ranged','ドレイク',{col:'#d07858',burst:3}),wyvern:mob('ワイバーン',31,'風','charge','ワイバーン',{col:'#9fd0c8'}),succubus:mob('サキュバス',33,'無','ranged','アンブラ',{col:'#d078d8',burst:3}),alraune:mob('アルラウネ',33,'土','ranged','シルフ',{col:'#80c070',burst:2}),yokaiFox:mob('妖狐',34,'火','charge','フェンリル',{col:'#e8b060'}),darkElf:mob('ダークエルフ',35,'無','ranged','ゴブリンメイジ',{col:'#b078d8',burst:3}),elderDrake:mob('エルダードレイク',36,'火','ranged','ドレイク',{col:'#ff8060',burst:4,r:22}),mirage:mob('ミラージュ',34,'無','ranged','ノーム',{col:'#d0c0ff',burst:3,mv:'weave'}),nineTail:mob('九尾',74,'火','ranged','フェンリル',{col:'#e8c070',burst:5,r:24}),
  seaSerpent:mob('シーサーペント',44,'水','charge','リンドヴルム',{col:'#5ac0d0',r:23}),giantTurtle:mob('ジャイアントタートル',44,'水','melee','ロックスライム',{col:'#70a878',spd:.45,r:24}),frostDragon:mob('フロストドラゴン',45,'水','ranged','フロストドラゴン',{col:'#bfefff',burst:4,r:24}),lindwurm:mob('リンドヴルム',46,'無','charge','リンドヴルム',{col:'#b0a0d0',r:24}),troll:mob('トロル',44,'土','melee','トロル',{col:'#8fa060',r:24}),cyclops:mob('サイクロプス',45,'土','melee','サイクロプス',{col:'#b89050',r:24}),ogre:mob('オーガ',46,'土','melee','オーガ',{col:'#c09070',r:24}),earthDragon:mob('アースドラゴン',48,'土','ranged','アースドラゴン',{col:'#e0c060',burst:4,r:24}),ironGolem:mob('アイアンゴーレム',49,'土','melee','ロックスライム',{col:'#b8b8b8',r:24}),sandWorm:mob('サンドワーム',49,'土','charge','サイクロプス',{col:'#d0b070',r:24}),
  griffon:mob('グリフォン',52,'風','charge','グリフォン',{col:'#dfe8a0',spd:1.0}),thunder:mob('サンダーバード',53,'風','ranged','サンダーバード',{col:'#ffe14a',burst:3}),cerberus:mob('ケルベロス',54,'火','charge','ケルベロス',{col:'#a04a6a',r:23}),siren:mob('セイレーン',55,'水','ranged','ウンディーネ',{col:'#8fd8ff',burst:3}),pegasus:mob('ペガサス',55,'風','charge','ペガサス',{col:'#cfe0f0'}),jinn:mob('ジン',56,'風','ranged','ルクス',{col:'#bfe8ff',burst:4}),unicorn:mob('ユニコーン',56,'水','ranged','ユニコーン',{col:'#f0e8ff',burst:3}),vampire:mob('ヴァンパイア',58,'無','ranged','ナイトメア',{col:'#d080b0',burst:4}),nightmare:mob('ナイトメア',58,'無','charge','ナイトメア',{col:'#b0a0d0'}),sentry:mob('セントリー',60,'無','ranged','ホブゴブリン',{col:'#a8b0b8',burst:3}),phantom:mob('幻影',60,'無','charge','スピリット',{col:'#b0a0d0'}),guardian:mob('ガーディアン',62,'無','melee','ロックスライム',{col:'#a8b0b8',r:24}),
  crystalGolem:mob('クリスタルゴーレム',62,'水','melee','ジェムスライム',{col:'#aef0ff',r:24}),gemKing:mob('ジェムキング',64,'水','ranged','ジェムスライム',{col:'#ffd27a',burst:4,r:24}),fenrir:mob('フェンリル',64,'水','charge','フェンリル',{col:'#cfe8f0'}),hydra:mob('ヒュドラ',66,'水','ranged','リンドヴルム',{col:'#7fd0a0',burst:5,r:24}),phoenix:mob('フェニックス',68,'火','ranged','フェニックス',{col:'#ffb050',burst:5}),sentryCore:mob('セントリー・コア',76,'無','ranged','ルクス',{col:'#bcd0ff',burst:4}),lich:mob('リッチ',76,'無','ranged','アンブラ',{col:'#b08cff',burst:5}),ancientDragon:mob('エンシェントドラゴン',80,'無','ranged','エンシェントドラゴン',{col:'#ff2d6d',burst:5,r:25}),titanGolem:mob('タイタンゴーレム',80,'土','melee','ロックスライム',{col:'#c0b090',r:26}),
  prismWraith:mob('プリズム・レイス',84,'無','ranged','プリズムバード',{col:'#dffaff',burst:5}),progenitorVampire:mob('真祖ヴァンパイア',86,'無','ranged','ナイトメア',{col:'#ff80b0',burst:5}),manaAnomaly:mob('マナ・アノマリー',88,'無','ranged','ルクス',{col:'#bdf0ff',burst:5}),arcWarden:mob('アーク・ウォーデン',88,'無','melee','ルクス',{col:'#bcd0ff',r:25}),voidSpirit:mob('ヴォイド・スピリット',92,'無','ranged','アンブラ',{col:'#9a7adf',burst:5}),ancientLich:mob('エンシェント・リッチ',93,'無','ranged','アンブラ',{col:'#c090ff',burst:6}),calamityDragon:mob('厄災竜カラミティ',95,'火','ranged','エンシェントドラゴン',{col:'#ff4060',burst:6,r:26}),behemoth:mob('ベヒモス',95,'土','charge','オーガロード',{col:'#b89070',r:26}),arcGuardian:mob('アーク・ガーディアン',97,'無','ranged','ルクス',{col:'#d0e0ff',burst:6,r:26})
 };
 Object.assign(ET,{sprite:ET.hornRabbit,boar:ET.manaWolf,hornet:ET.goblinArcher,fungus:ET.goblinMage,wisp:mob('ウィル・オ・ウィスプ',16,'火','ranged','ウィル・オ・ウィスプ',{col:'#ff8a4a',burst:3}),salaman:mob('サラマンダー',16,'火','melee','サラマンダー',{col:'#ff5a2a'}),magma:mob('フレイムスライム',17,'火','charge','フレイムスライム',{col:'#ff3a1a'}),babyDragon:mob('ベビードラゴン',9,'火','ranged','ベビードラゴン',{col:'#e8a060',burst:2}),mantis:mob('マナディア',14,'風','melee','マナディア',{col:'#9ee06a',spd:1.1}),pixie:ET.sylph,frost:ET.kelpie,icewisp:mob('ウンディーネ',24,'水','ranged','ウンディーネ',{col:'#bfefff',burst:3}),crystalan:ET.gemSlime,wraith:mob('スピリット',32,'無','ranged','スピリット',{col:'#9a7adf',burst:3}),shade:mob('アンブラ',56,'無','melee','アンブラ',{col:'#7a708a'}),abyssal:mob('ルクス',56,'無','ranged','ルクス',{col:'#9a6aa0',burst:4}),devour:ET.cerberus,revenant:mob('オーガロード',72,'無','melee','オーガロード',{col:'#6a5a7a',r:24}),doomeye:ET.drake,cloud:ET.pegasus,yeti:ET.fenrir,stormDragon:mob('ストームドラゴン',46,'風','ranged','ストームドラゴン',{col:'#9fe8d0',burst:4,r:24})});
 return {ET,ENEMY_RANK:{normal:{hpMul:1,atkMul:1,scale:1,expRate:0.5,sync:false},rare:{hpMul:4,atkMul:1.8,scale:1.35,expRate:0.7,sync:false,announce:true},elite:{hpMul:50,atkMul:3,scale:3,expRate:0.8,sync:true,announce:true},boss:{hpMul:1,atkMul:1,scale:1,expRate:0.7,sync:true,announce:true},demon:{hpMul:50,atkMul:3,scale:1,expRate:0.8,sync:true,announce:true,caster:true}}};
})();
